"""add_table_file

Revision ID: 093e4a2a72e7
Revises: e8581772ef5e
Create Date: 2023-09-02 17:28:12.594006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "093e4a2a72e7"
down_revision: Union[str, None] = "e8581772ef5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("path", sa.String(length=2048), nullable=False),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("is_downloadable", sa.Boolean(), nullable=False),
        sa.Column("creator_id", sa.UUID(), nullable=True),
        sa.Column("deleted", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file")
    # ### end Alembic commands ###
