"""foreign_key_on_delete_cascade_added

Revision ID: 7dd746347285
Revises: bae1f0d92988
Create Date: 2023-09-04 03:45:11.732419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7dd746347285"
down_revision: Union[str, None] = "bae1f0d92988"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("file", "creator_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint("file_creator_id_fkey", "file", type_="foreignkey")
    op.create_foreign_key(
        None, "file", "user", ["creator_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "file", type_="foreignkey")
    op.create_foreign_key(
        "file_creator_id_fkey", "file", "user", ["creator_id"], ["id"]
    )
    op.alter_column("file", "creator_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
